//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopEn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public int MACT { get; set; }
        public Nullable<int> MAHD { get; set; }
        public Nullable<int> MASP { get; set; }
        public Nullable<int> MACB { get; set; }
        public Nullable<decimal> GIA { get; set; }
    
        public virtual COMBO COMBO { get; set; }
        public virtual HOADON HOADON { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
