CREATE DATABASE QLBHDT
GO
USE master
DROP DATABASE QLBHDT

USE QLBHDT
GO

CREATE TABLE SANPHAM (MASP INT PRIMARY KEY IDENTITY, TENSP NVARCHAR(50), LOAI CHAR(6), GIA MONEY, SOLUONG INT, IMAGE VARCHAR(20))
ALTER TABLE SANPHAM ADD CONSTRAINT FK_LOAI FOREIGN KEY (LOAI) REFERENCES LOAI_SP(LOAI)

CREATE TABLE LOAI_SP (LOAI CHAR(6) PRIMARY KEY NOT NULL, TEN NVARCHAR(15))

CREATE TABLE COMBO (MACB INT PRIMARY KEY IDENTITY, TENCB NVARCHAR(50), GIA MONEY, IMAGE VARCHAR(20))

CREATE TABLE CT_CB_SP (MACB INT NOT NULL, MASP INT NOT NULL, PRIMARY KEY (MACB, MASP), SOLUONG INT)
ALTER TABLE CT_CB_SP ADD CONSTRAINT FK_CB FOREIGN KEY (MACB) REFERENCES COMBO(MACB)
ALTER TABLE CT_CB_SP ADD CONSTRAINT FK_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)

CREATE TABLE KHACHHANG (MAKH INT PRIMARY KEY IDENTITY, TENKH NVARCHAR(50), DIACHI NVARCHAR(50), SDT CHAR(10), NGAYSINH DATE, EMAIL CHAR(50), PASSWORD CHAR(50))

CREATE TABLE HOADON (MAHD INT PRIMARY KEY IDENTITY, NGAYLAPHD DATETIME, MAKH INT , MATT INT)
ALTER TABLE HOADON ADD CONSTRAINT FK_TT FOREIGN KEY (MATT) REFERENCES TRANGTHAI_HD(MATT)
ALTER TABLE HOADON ADD CONSTRAINT FK_KH FOREIGN KEY (MAKH) REFERENCES KHACHHANG(MAKH)

CREATE TABLE CTHD (MACT INT PRIMARY KEY IDENTITY, MAHD INT , MASP INT , MACB INT , GIA MONEY)
ALTER TABLE CTHD ADD CONSTRAINT FK_CTHD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)
ALTER TABLE CTHD ADD CONSTRAINT FK_HD_SP FOREIGN KEY (MASP) REFERENCES SANPHAM(MASP)
ALTER TABLE CTHD ADD CONSTRAINT FK_HD_CB FOREIGN KEY (MACB) REFERENCES COMBO(MACB)

CREATE TABLE TRANGTHAI_HD (MATT INT PRIMARY KEY IDENTITY(1,1), TEN NVARCHAR(20))

CREATE TABLE NHANVIEN (MANV INT PRIMARY KEY IDENTITY, TENKH NVARCHAR(50), DIACHI NVARCHAR(50), SDT CHAR(10), NGAYSINH DATE, MAVT CHAR(4), EMAIL CHAR(50), PASSWORD CHAR(50))
ALTER TABLE NHANVIEN ADD CONSTRAINT FK_VT FOREIGN KEY (MAVT) REFERENCES VITRI(MAVT)

CREATE TABLE VITRI (MAVT CHAR(4) PRIMARY KEY, TEN NVARCHAR(15))


INSERT INTO dbo.LOAI_SP
        ( LOAI, TEN )
VALUES  ( 'DT', -- LOAI - char(6)
          N'Điện thoại'  -- TEN - nvarchar(15)
          )
INSERT INTO dbo.SANPHAM
        (  TENSP, LOAI, GIA, SOLUONG, IMAGE )
VALUES  ( 
          N'Điện thoại iPhone 12 128GB', -- TENSP - nvarchar(50)
          'DT', -- LOAI - char(6)
          20000000, -- GIA - money
          10, -- SOLUONG - int
          'iphone12.jpg'  -- IMAGE - varchar(20)
          )
INSERT INTO dbo.SANPHAM
        (  TENSP, LOAI, GIA, SOLUONG, IMAGE )
VALUES  ( 
          N'Điện thoại Samsung 128GB', -- TENSP - nvarchar(50)
          null, -- LOAI - char(6)
          20000000, -- GIA - money
          10, -- SOLUONG - int
          'sam11.jpg'  -- IMAGE - varchar(20)
          )

SELECT *
FROM dbo.SANPHAM